# Generated by Django 3.2.16 on 2022-10-29 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choices',
            name='replier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
