# Generated by Django 3.2.16 on 2022-10-29 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_auto_20221029_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='replier',
        ),
        migrations.AddField(
            model_name='choices',
            name='replier',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
